<?php

/**
 * Implements hook_block_info().
 */
function noon48_config_block_info() {
  // This example comes from node.module.
  $blocks['twitter'] = array(
    'info' => t('twitter feed custom'),
    'cache' => DRUPAL_NO_CACHE,
  );

 $blocks['twitter2'] = array(
    'info' => t('twitter feed custom No 2'),
    'cache' => DRUPAL_NO_CACHE,
  );

  $blocks['webformblock'] = array(
    'info' => t('email form'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}


/**
 * Implements hook_block_info().
 */
function noon48_config_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'twitter':
      //$block['subject'] = t('Syndicate');
      $block['content'] = array(
        '#markup' => twitter_pull_render('@No_On_Prop48', $title = FALSE, $num_items = 6, $themekey = NULL),
      );
      break;

    case 'twitter2':
      //$block['subject'] = t('Syndicate');
      $block['content'] = array(
        '#markup' => twitter_pull_render('@No_On_Prop48', $title = FALSE, $num_items = 1, $themekey = NULL),
      );
      break;

    case 'webformblock':
      if (user_access('access content')) {
        //$block['subject'] = t('Recent content');
        $form = drupal_get_form('noon48_config_email_form');
        $block['content'] = drupal_render($form);
      }
      break;
  }

  return $block;
}


/**
 * Custom email entry form.
 */
function noon48_config_email_form($form, $form_state) {
  // Get the canned messages terms
  $form['#action'] = url('node/12');
  $form['email'] = array(
    '#title' => t('Email'),
    '#type' => 'textfield',
  );
  $form['submit'] = array(
    '#value' => t('Submit'),
    '#type' => 'submit',
  );
  return $form;
}


/**
 * Custom email entry form.
 */
function noon48_config_form_webform_client_form_12_alter(&$form, &$form_state) {
  if (!empty($_POST['email'])) {
    $form['submitted']['email']['#default_value'] = $_POST['email'];
  }
}